name: courtify
description: "파이썬기반딥러닝 수업 프로젝트 MVP 용 앱/웹 UI 개발 Flutter 프로젝트. 붉은 색을 테마로 법률문을 입력받아 AI API가 자동으로 기사문으로 작성해줌. 이를 기사 형식으로 표시하는 앱/웹을 개발."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  google_sign_in: ^6.2.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - Assets/

  fonts:
    - family: SUIT
      fonts:
        - asset: Assets/Fonts/SUIT-Thin.otf
          weight: 100
        - asset: Assets/Fonts/SUIT-ExtraLight.otf
          weight: 200
        - asset: Assets/Fonts/SUIT-Light.otf
          weight: 300
        - asset: Assets/Fonts/SUIT-Regular.otf
          weight: 400
        - asset: Assets/Fonts/SUIT-Medium.otf
          weight: 500
        - asset: Assets/Fonts/SUIT-SemiBold.otf
          weight: 600
        - asset: Assets/Fonts/SUIT-Bold.otf
          weight: 700
        - asset: Assets/Fonts/SUIT-Heavy.otf
          weight: 800
        - asset: Assets/Fonts/SUIT-ExtraBold.otf
          weight: 900