// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0HQhyYMiyENSzP1pWkxj5FYTnTmKoiQM',
    appId: '1:75065448848:web:39b9541294f9ebb30c3b15',
    messagingSenderId: '75065448848',
    projectId: 'courtify-298fe',
    authDomain: 'courtify-298fe.firebaseapp.com',
    storageBucket: 'courtify-298fe.firebasestorage.app',
    measurementId: 'G-28ZXGCJMK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC53wilJzodjZ7tsEHCwmBzpGYZmBVBs7E',
    appId: '1:75065448848:android:0f998d91b9478e0c0c3b15',
    messagingSenderId: '75065448848',
    projectId: 'courtify-298fe',
    storageBucket: 'courtify-298fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhO-4MTPuHt6LvpgcGOxlxywpSQ5I00-o',
    appId: '1:75065448848:ios:039c8a86dca194eb0c3b15',
    messagingSenderId: '75065448848',
    projectId: 'courtify-298fe',
    storageBucket: 'courtify-298fe.firebasestorage.app',
    iosClientId: '75065448848-o118m7sm2o0hm2a15fvhi3t4ides6k81.apps.googleusercontent.com',
    iosBundleId: 'com.example.courtify',
  );
}
